### ISSUE TITLE
Clicking on event name is not discoverable

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#11]
Consider adding a green "play" button that will also do the same thing.

**Comment by evanfarrar** [comment]
I've introduced a second style of button, a yellow link, in line with the look and feel provided by LY. Hopefully the differentiated text color and stronger hover state will satisfy the goals of this ticket.

I'd really rather not use a "play" button, it's too suggestive of a particular thing and not really in sync with current look and feel. Also, I'd rather not introduce a new type of button that is used in a unique way. Perhaps if we could categorize our buttons that we need to differentiate visually, I could better see the need for a button that looks different than the other two. For example, "visiting" versus "changing" versus "deleting". After this exercise we might discover a need, categorically, for a type of button that points to the right and is green.
