### ISSUE TITLE
WINNER Screen: text alignment

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#29]
Can we try one of the following:

1) right justify the text (including next race) since the seconds side of the colon will always have the same number of characters?

2) center the text (including next race).

The WINNER IS NAME looks great, but the rest currently looks more like a test screen.

**Comment by evanfarrar** [comment]
I've made the winner screen look more like the mockups from LY. I don't think i can center the next race button, i could move it to the top, is that better?

Overall, I think the screen looks more "done" which is what I believe you were going for with this ticket.
