### ISSUE TITLE
Event Screen: move delete buttons away from edit / start race buttons

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#37]
Can we try moving the red delete X on the left side of the text?  That way we don't accidentally click on delete when we were intending to edit.

I have already deleted a few things I didn't want to by accident.

**Comment by evanfarrar** [comment]
I've moved them farther apart and released it in 0.2-27. I'd really like to keep "here is this thing" and "here are things you can do to said thing" grouped semantically in this instance. if deletion is a recurring usability problem, we can add a confirm or undo.

**Comment by jonfen** [comment]
If we are sorting by best time, we probably should show the time here too, which would probably move them closer.
