### ISSUE TITLE
Request: Defining Category tab visibility

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#4]
The "categories" tab should only be seen from the "events" (formerly tournaments) screen since that is where it will mostly be used from.

**Comment by evanfarrar** [comment]
There are two things that have to happen to ensure the functionality is still available else where: users need to be able to add a category while adding a racer, and users should be able to delete categories from the configuration area. Once that is done, the categories tab can go away.

**Comment by jonfen** [comment]
I added separate Issues for both of those cases.
