### ISSUE TITLE
Keep MouseOver Consistent

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#49]
Cal: "In some places the MouseOver goes from grey to black, in other places it goes from black to black with underlining.  Can we keep it consistent?  Preferably everything going from grey to black and ditching the underlining?"

**Comment by evanfarrar** [comment]
e1d5837567cae4adda0d986fc5ca1950aa6de77c fixes this. not yet released.

**Comment by evanfarrar** [comment]
released 0.2-29
