### ISSUE TITLE
"Index" term is confusing

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#5]
Change "Index" to "Back" or "Save and go back"

**Comment by evanfarrar** [comment]
Probably going to change it to "Return To Main Menu"...."back" or "save and go back" are both different than "index" which is the main menu (currently "categories / tournaments / configuration")

**Comment by evanfarrar** [comment]
The index button has been changed to "Return to Main Menu"

**Comment by jonfen** [comment]
I would just say "Main Menu" the "return to" part is redundant and hopefully obvious.

**Comment by evanfarrar** [comment]
ok, well, I'll take that into consideration.
