### ISSUE TITLE
Event-->Add a new Racer-->Assign Category: UI Change

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#52]
Instead of using a drop down box to select categories and have them appear below, get rid of the dropdown, list out all the categories, and put a checkbox to the left of each one.  (And also have a link to the add a new category form.)

This method would:
1) require less clicks
2) less screen movement
3) improve the tab order

**Comment by evanfarrar** [comment]
bcec8b0c3557dfa52e005a174c27551b4f8130a3 changes this. it is not yet released

**Comment by evanfarrar** [comment]
released in 0.2-28

**Comment by evanfarrar** [comment]
released in 0.2-28
