### ISSUE TITLE
Event-->Add a new racer-->Cancel

### ISSUE THREAD

**Issue by calvertcruz** [evanfarrar/opensprints#62]
After canceling a racer, it still appears in the racers inputbox.

**Comment by jonfen** [comment]
Cal, are you referring to this bug?  http://github.com/evanfarrar/opensprints/issues/#issue/41

If so, I think Evan fixed that.

**Comment by evanfarrar** [comment]
I didn't fix it 21 hours ago, but I did fix it 3 hours ago. In 0.2-29 and above, no more phantom crap.
