### ISSUE TITLE
Get Ready-->Stop Countdown: freezes software

### ISSUE THREAD

**Issue by calvertcruz** [evanfarrar/opensprints#76]
Clicking this button freezes the software. Then the software returns to the main menu screen. When returning to the racers/races screen the race that was stopped is struck-through, even though there was no actual race.

**Comment by evanfarrar** [comment]
I can't replicate. Can you guys try replicating it with real electronics?

**Comment by lukeorland** [comment]
i could not repeat this with build 0.2-29 and a real arduino

**Comment by lukeorland** [comment]
closing.
