### ISSUE TITLE
Events-->Race-->Edit Race: green plus icons that shouldn't be there

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#79]
When someone is already assigned, you can't see their name, however you can see the green plus sign that was by their name still.

**Comment by evanfarrar** [comment]
Is this still a problem? I think it is a duplicate of #73, which I closed.

**Comment by lukeorland** [comment]
i'm not seeing this on build 0.2-29. i will try on an early build that supports > 2 racers.

**Comment by lukeorland** [comment]
closing
