### ISSUE TITLE
Navigation Error / Side effect

### ISSUE THREAD

**Issue by jonfen** [evanfarrar/opensprints#9]
When clicking on "new category" then canceling by clicking on "Index" we are brought back to the main screen instead of the "Categories screen"

Solution: add a "cancel" button and change "index" to "main menu"

**Comment by evanfarrar** [comment]
At least the "index" portion of this should be handled by fixing #5 the other half still needs addresed with a cancel and/or go back button

**Comment by evanfarrar** [comment]
Since the cancel half of this is mentioned by #12 and the index portion has already been addressed by #5 I'm going to close this ticket.. I'm not trying to ignore the problem, I am just trying to organize the issues into the way they are going to be split into units of work.
